apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetapp-deployment  # Name of deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aspnetapp   # Select Pods that match these labels
  template:
    metadata:
      labels:
        app: aspnetapp   # Labels that Pods created by the Deployment will have
      annotations:
        vault.hashicorp.com/agent-inject: "true"  # Enable Vault Agent Injection
        vault.hashicorp.com/role: 'internal-app'
        vault.hashicorp.com/agent-inject-secret-database-config.txt: 'secret/data/docker-credentials'
    spec:
      serviceAccountName: internal-app
      containers:
      - name: aspnetapp   # Giving a name for the container being deployed 
        image: jlimhy/aspnetapp:latest   # Select docker image you have on your machine
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service  
metadata:
  name: aspnetapp-service  # Name of Service
spec:
  selector:
    app: aspnetapp   # Looks for pods with "aspnetapp" in the name
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer  # Expose the service as LoadBalancer
