name: Retrieve Secrets from Vault

on:
  push:
    branches:
      - main

jobs:
  retrieve-secrets:
    runs-on: self-hosted  # Use your self-hosted runner

    steps:
      # Step 1: Checkout the code (optional if you don't need the repository files)
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Retrieve Docker credentials from Vault
      - name: Retrieve Docker Credentials
        id: vault-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: http://localhost:8200  # Replace with your Vault URL if different
          method: approle
          roleId: 940199af-668a-0c10-0f9e-eab2caaf6e7a  # Your Vault Role ID
          secretId: 679c1d9f-cf79-b336-48a7-f9649cdb2d99  # Your Vault Secret ID
          secrets: |
            secret/data/docker-credentials docker-username | DOCKER_USERNAME ;
            secret/data/docker-credentials docker-password | DOCKER_PASSWORD

      - name: echo
        run: |
          echo ${{ steps.vault-secrets.outputs.DOCKER_USERNAME }}
          echo ${{ steps.vault-secrets.outputs.DOCKER_PASSWORD }}
            
      - name: Build Docker image
        run: |
          docker build -t jlimhy/aspnetapp:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ steps.vault-secrets.outputs.DOCKER_USERNAME }}
          password: ${{ steps.vault-secrets.outputs.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push jlimhy/aspnetapp:latest

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f ./deployment.yaml
